# start with MySQL, then Node.js, and lastly React
# ports: MySQL -> 3306, Node.js -> 5000, React -> 3000

version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
