# start with MySQL, then Node.js, and lastly React
# ports: MySQL -> 3307, Node.js -> 5000, React -> 3000

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306" # Expose MySQL (3306) on port 3307
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 30s # give MySQL time to start

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_DATABASE: wcu_db
      PORT: 5000
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  db_data: